name: Run train.py on changes to chatplm_brain.xlsx
on:
  push:
    paths:
      - 'chatplm/data/chatplm_brain.xlsx'
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.x
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run train.py script
        run: python chatplm/train.py
      - name: Push changes
        run: |
          git config --global user.name 'amyr11'
          git config --global user.email 'amyrfrancisco11@gmail.com'
          git commit -am "(Automated) Re-trained model"
          git push
        env:
          PAT: ${{ secrets.PUSH_SECRET }}
